image:
  - Visual Studio 2019

cache:
  - c:\users\appveyor\clcache
  - c:\local\boost_1_69_0

environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIBRARYDIR: C:\local\boost_1_69_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

install:
  - ps: Write-Host "Checking for Boost 1.69.0 x64...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x64...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.69.0 x64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x64 installed!" -ForegroundColor Green

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 .. -DARCH=default -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild Avrio.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir Avrio-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe Avrio-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE Avrio-%APPVEYOR_REPO_TAG_NAME%
  - 7z a Avrio-%APPVEYOR_REPO_TAG_NAME%-windows.zip Avrio-%APPVEYOR_REPO_TAG_NAME%
  - copy Avrio-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: Avrio-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: AvrioRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: GD9rRRErKPfPZM71xvjImOjRQiTNLp4nRIPygmfb+aRzU+V/Wyp5Z5zIgt5rXGf7
    artifact: AvrioRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: avrio-project/avrio
      appveyor_repo_tag: true
