language: cpp

cache:
  ccache: true
  directories:
  - "/home/travis/toolchain"

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: ppa:mhier/libboost-latest
        - ubuntu-toolchain-r-test
        packages:
        - libboost-all-dev
        - libssl-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: ppa:mhier/libboost-latest
        - ubuntu-toolchain-r-test
        packages:
        - libboost-all-dev
        - libssl-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"
  - os: linux
    dist: bionic
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

script:
- eval $MATRIX_EVAL
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- ${STRIP} Avrio*
- rm -rf avrio-${TRAVIS_TAG}
- mkdir avrio-${TRAVIS_TAG}
- cp Avrio* avrio-${TRAVIS_TAG}/
- cp ../../LICENSE avrio-${TRAVIS_TAG}/
- tar cvfz avrio-${TRAVIS_TAG}-${LABEL}.tar.gz avrio-${TRAVIS_TAG}/

deploy:
  provider: releases
  edge: true
  api_key:
    secure: "vtpX3y213GkAE+SFcMyUCvyoRVdtAyLxaO+a+s/UhWMeyE01/92vArfUbxanYELRjCXQncq4fHjFYhumR4wrUcnucY3yXsiCMM8xsEDQnI5DjXZr305Dricgqy4CO24uP5cvh67aBvIHgVV+p6mMppAY38qDI3EIs8TpZuI5k5ayF5ChRYvH6Jlix4x+0AHyVu01/zI8h05NZhxArr4nUquoP2IWOmWp2EURLPlmbPDrwy9Pc1dqGiW+sTDW+uGNBdsUUhJw9ia1O47HmTCJKdf5Jt/nq9bgOg2k75x2ZG3JS9+Y3dGh2TdwBFqXYbR/fQJqP1OjtFdfHHzZcZixOFjZe48NPZiXkTLUFP679pEXirHzLPg9W872/qchQ894/XFGZaoH7NnnWTTs4/kgjmrNEypPKy17BnXCRmVSS5egrRSgFXdUAT2gazwS2l7dv5iW8a2SqoxWQwtsP/gb3F21gNOAIbva0wKSNQiMuQmT+Uu+kjBGf6qxLSaUFOdciu8fDDyimhpU9PYca3T3mqUezNLxehFG8fkEVAXWeNhiZIVthHmy7PeMpP1/tutV6w0Tp48cacIIuN8cQ1/X7pmW4nCv/4Qw2TdvWdlwF9sE53xWxedWwc/biyOCghF3XuRi2vbDc6dnwNdtAfG9khDrRrba1rbYFt5c2Q0hfJ0="
  file:
    - avrio-${TRAVIS_TAG}-${LABEL}.tar.gz
  cleanup: false
  on:
    repo: avrio-project/avrio
    condition: "$_DEPLOYABLE = true"
    tags: true
    all_branches: true
